Parameters:
  StackParentName:
    Type: String
    Description: "Name of parent stack"

  StackSsmParamPrefix:
    Type: String
    Description: "Prefix for SSM Params created by this stack"

  VpcId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Description: "VPC ID"

  VpcSubnets:
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>
    Description: "VPC Subnets ALB will cover"

  AlbProtocol:
    Type: String
    Description: "Protocol for ALB connections"
    AllowedValues:
      - "HTTPS"
      - "HTTP"


Mappings:
  ProtocolMap:
    HTTP:
      Port: 80
      UrlPrefix: "http://"
    HTTPS:
      Port: 443
      UrlPrefix: "https://"


Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupDescription: "Access ALB in front of ECS"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${StackParentName}-alb"

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name:
        Ref: StackParentName
      Subnets:
        Ref: VpcSubnets
      SecurityGroups:
        - Ref: AlbSecurityGroup
      Tags:
        - Key: Name
          Value:
            Ref: StackParentName

  # ALB's need a target group so we create this dummy default one.
  AlbDefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Ref: VpcId
      Port:
        Fn::FindInMap:
          - ProtocolMap
          - Ref: AlbProtocol
          - Port
      Protocol:
        Ref: AlbProtocol

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Ref: Alb
      Port:
        Fn::FindInMap:
          - ProtocolMap
          - Ref: AlbProtocol
          - Port
      Protocol:
        Ref: AlbProtocol
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: AlbDefaultTargetGroup

  AlbSecurityGroupIdSsmParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Join:
          - '/'
          - - Ref: StackSsmParamPrefix
            - "AlbSecurityGroupId"
      Description: "ALB Security Group ID"
      Type: String
      Value:
        Ref: AlbSecurityGroup

  AlbListenerArnSsmParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Join:
          - '/'
          - - Ref: StackSsmParamPrefix
            - "AlbListenerArn"
      Description: "ALB Listener Arn"
      Type: String
      Value:
        Ref: AlbListener


  AlbUrlSsmParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Join:
          - '/'
          - - Ref: StackSsmParamPrefix
            - "AlbUrl"
      Description: "ALB URL"
      Type: String
      Value:
        Fn::Join:
          - ''
          - - Fn::FindInMap:
              - ProtocolMap
              - Ref: AlbProtocol
              - UrlPrefix
            - Fn::GetAtt:
              - Alb
              - DNSName

